# Auxiliary functions

Objective: Provide functions and lines of code to assist the user to prepare, process and analyze Landsat 8/7 data for classification purposes.

## Cloud and cloud shadow masking

[*Section Snapshot at GEE*](https://code.earthengine.google.com/cd7747671a8a2d411ae86afd1aebf084){target="_blank"}

This section demonstrates a way of masking clouds and cloud shadow pixels from Landsat 8/7 Surface Reflectance data based on file metadata. This function was created based on the documentation available for Landsat 8/7. Values for pixel bit and pixel band were found [*here.*](https://www.usgs.gov/core-science-systems/nli/landsat/landsat-collection-1-level-1-quality-assessment-band?qt-science_support_page_related_con=0#qt-science_support_page_related_con){target="_blank"}

Then use this function
```{r eval=FALSE}
function maskL8sr(image) {
  // #Bits 3 and 5 are cloud shadow and cloud, respectively.
  var cloudShadowBitMask = ee.Number(2).pow(3).int();
  var cloudsBitMask = ee.Number(2).pow(5).int();
  // #Get the pixel QA band.
  var qa = image.select('pixel_qa');
  // #Both flags should be set to zero, indicating clear conditions.
  var mask = qa.bitwiseAnd(cloudShadowBitMask).eq(0)
      .and(qa.bitwiseAnd(cloudsBitMask).eq(0));
  // #Return the masked image, scaled to [0, 1].
  return image.updateMask(mask).divide(10000).copyProperties(image, ["system:time_start"]);
}
```

## Spectral Indices

This section demonstrates how to calculate and add spectral indices to each scene of a Landsat 8/7 image collection. The function below calculates and add spectral indices to an image collection taking into account Landsat 8 spectral bands (Table 1):